name: main
on: [push, pull_request]

jobs:
  main:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          mamba-version: "*"
          environment-file: conda/local.yaml
          channels: conda-forge,nodefaults
          activate-environment: waveapp
          use-mamba: true
          miniforge-variant: Mambaforge

      - name: Install dependencies
        run: |
          curl -sSL https://install.python-poetry.org/ | python -
          export PATH="$HOME/.poetry/bin:$PATH"

      - name: Install from poetry
        run: poetry config virtualenvs.create true && poetry install

      - name: Starting backend
        run: bash scripts/ci/backend.sh > /dev/null 2>&1 &

      - name: Run wave app
        run: |
          sleep 5 && curl -i http://localhost:10101 2>/dev/null | head -n 1 | cut -d$' ' -f2

      - name: Setup tmate session
        if: "${{ failure() }}"
        uses: mxschmitt/action-tmate@v3

          
